add poetry
TOMToolkit/tom_fink pull request #41
Opened 2024-03-14 22:45 UTC by jchate6

Adds Poetry

2024-03-15 11:50 UTC, JulienPeloton commented
Thanks @jchate6 for the transition to `poetry`!

2024-03-15 21:31 UTC, phycodurus approved these changes

2024-03-18 22:17 UTC, phycodurus requested changes

2024-03-18 22:17 UTC, phycodurus commented on pyproject.toml
> +description = "The Fink Alert Broker Module for the TOM Toolkit. Fink is a broker currently connected to ZTF. More information on Fink at https://fi"
typo here in url?

2024-03-18 22:17 UTC, phycodurus commented on tom_fink/fink.py
> +    The list of arguments for retrieving SSO data can be found through {}/api/v1/sso.
this should be an f-string instead of using `.format()` 20-lines below.

2024-03-18 22:25 UTC, phycodurus approved these changes
thanks!

2024-03-18 22:33 UTC, merged